# Generated by Django 2.0.6 on 2018-06-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0002_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
