# Generated by Django 2.0.6 on 2018-06-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0005_auto_20180609_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='albums',
            name='release_date',
        ),
    ]
