# Generated by Django 2.0.6 on 2018-06-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0006_auto_20180611_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='artwork',
        ),
    ]
