# Generated by Django 2.0.6 on 2018-06-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0007_remove_music_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cover',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
