# Generated by Django 2.0.6 on 2018-06-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0008_artist_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albums',
            old_name='artist_id',
            new_name='artist',
        ),
    ]
