# Generated by Django 2.0.6 on 2018-06-12 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0009_auto_20180612_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spotify.Music')),
            ],
        ),
    ]
