# Generated by Django 2.0.6 on 2018-06-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0011_auto_20180614_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='track',
            field=models.ManyToManyField(to='Spotify.Music'),
        ),
    ]
